### ISSUE TITLE
Add update asset & new asset page

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#110]
New asset is actually already generated in vegaprotocol/data-node#79 but there's no page for it yet.

_Originally posted by @edd in https://github.com/vegaprotocol/documentation/issues/68#issuecomment-1160311712_

There is a code block for proposing an asset in the `_generated_` folder, but no page for it 

# Task
1. [x] Decide if it's one page for both asset proposals or two pages - **It's two**
2. [x] Create the appropriate MD with the new asset block embedded
3. [x] Update proposal generator to create an `updateAsset` proposals
4. [x] Add `updateAsset` to the appropriate page (see point 1)
