### ISSUE TITLE
Import API how-to guides

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#114]
# API how-tos on the old site
- [x] Get started with your first query to a Vega API
- [x] Learn how to sign transactions with Wallet signing
- [x] Start trading and Submit an order to a node
- [x] Find an Order by reference once submitted
- [x] Gather Market information required to trade
- [x] Learn how to Amend orders or Cancel orders
- [x] Check your Positions and balances for collateral
- [x] Download a List of orders and trades on Vega
- [x] Propose and Create markets using governance
- [x] List Proposals and How to vote using governance
- [x] Build real time feeds with Streaming events
- [x] How to find Trading fees and calculate Fee estimates for orders trading fees
- [x] Get started with Liquidity provision
- [x] Learn about blockchain time using Vega Time

# Source
https://github.com/vegaprotocol/docs/tree/master/content/docs/api-howtos

## Tasks per how-to
- [ ] Ensure script still works
- [ ] If not, fix it
- [ ] Otherwise, bring it over
- [ ] Revise formatting to fit Docusaurus

**Comment by edd** [comment]
Fixed in #165
