### ISSUE TITLE
Show version switcher

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#116]
The switch between release version is hidden while https://github.com/vegaprotocol/docs/ is still deployed at http://docs.fairground.vega.xyz. When we've moved over the tasks labelled with https://github.com/vegaprotocol/documentation/issues?q=is%3Aissue+is%3Aopen+label%3Amigration, it's no longer going to be confusing and we can make it show up 

# Tasks
- [x] Complete migration tasks
- [x] #116 
# Blocked by
- [x] #114
- [x] https://github.com/vegaprotocol/documentation/issues/155

# Followed by
- [ ] https://github.com/vegaprotocol/documentation/issues/117

**Comment by edd** [comment]
This will fix #104 automatically
