### ISSUE TITLE
Renamed versioned docs from x.xx.x to x.xx

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#129]
`0.50.2` is overly precise, for example. If we release another patch to that, making another entire copy of the docs folder seems like a more work than it's worth. We already label versions as `0.50.x`, so let's just fully commit to not updating paths based on a patch. This means that, for example, docs for `0.50.1` or `0.50.2` will no longer be available. This should be fine, as patch releases shouldn't contain major changes. 

# Tasks
- [ ] Update `versions.json` to 
- [ ] Renamed `versioned_docs` folders 
- [ ] Update `docusaurus.config.js`
- [ ] Test it
- [ ] Release it
