### ISSUE TITLE
Tag new docs version for 0.53

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#143]
This will be on testnet this week, so the testnet docs version needs to progress

# Tasks
- [x] Replace 0.52 with 0.53
- [x] Update `build.sh` versions to `0.53`
- [x] Regenerate GraphQL & GRPC
- [x] Add REST versions to docusaurus.config.js
- [x] Run `update.sh`
- [ ] Merge in #126
