### ISSUE TITLE
Remove 0.47.0 docs

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#146]
0.47.0 is now quite old, and the documentation is no longer relevant. Everything useful exists in later documentation versions. Keeping this old version around slows down the build, so let's remove it.

If it turns out to still be relevant, we can link to an older deploy of the docs, which still exist.

# Tasks
- [ ] Remove 0.47.0 folder
- [ ] Remove version from `versions.json`
- [ ] Remove from `docusaurus.config.js`
- [ ] Enjoy faster build

This also helps us along with #129
