### ISSUE TITLE
Cut python requirement from build.sh

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#147]
The very handy script for fetching protos/graphQL schema from private repos is no longer required, as they are public. As such the python setup can be retired in favour of a one line curl/wget

# Tasks
- [ ] Remove `github_get_file`
- [ ] Remove venv setup and related from `build.sh`
- [ ] Remove requirements.txt
- [ ] Replace with CURL
