### ISSUE TITLE
Integrate NetworkParameter component in to Concepts docs

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#157]
Follow on from #148 - make it more elegant.

# An OK example
<img width="898" alt="Screenshot 2022-07-25 at 15 52 07" src="https://user-images.githubusercontent.com/6678/180807558-a422324b-24eb-4d31-942c-3f8ea34c0847.png">

This page was written with the component in mind. It's not clear to the average user just on sight alone that a network parameter set this value, but it is clear wht the number is. It's also a bit weird that the text around it doesn't actually know that the value is 0.

# An example of where it isn't good
This document was written intentionally not to reference the value, but how to find the value - by naming the network parameter. Simply jamming in the current value after the name is pretty rubbish:
<img width="825" alt="Screenshot 2022-07-25 at 15 51 47" src="https://user-images.githubusercontent.com/6678/180807204-b8488ae3-1e31-4e4b-a899-3127907b8e58.png">

Either we need to reformat the message when the value and label are shown, or... something? 🤷 

# Tasks
- [ ] @edd & @candida-d to decide what good looks like
- [ ] @edd to fix component to do the above
- [ ] @edd to extend the component to allow some sane formatting for values besides tokens
- [ ] Both to reformat the Concepts pages to use the component

**Comment by edd** [comment]
Closed by #177
