### ISSUE TITLE
Make a component to show network parameters and their current value

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#158]
Some documentation needs to refer to configuration that is set by the network parameters, which means they can be changed by governance. We don't want to add values that will go out of date, so instead let's make a component that can show the currently configured value.

# Tasks (v1)
- [x] Create a react componenet that can display a single network paramter
- [x] Make it able to show just the network parameter name, the name and value, or just the value
- [x] Make it link to the Block Explorer > Network Parameters page so the user can see how the value was set

# Follow up
#157
