### ISSUE TITLE
Validator improvements

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/documentation#253]
**Tasks**

- [X] Review Calum and [Jon?]'s vega.xyz planning doc: https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764532039890120&cot=14 
- [X] Get familiar with docs content e.g. https://docs.vega.xyz/docs/mainnet/concepts/vega-chain#validating-nodes
- [X] Meet with Candida when's she's had some time to think about desired outcomes for this task
- [X] Restructure node operator guides into "get started" and "how-to" sections
- [x] Check compatibility with [Candida's upcoming PR](https://deploy-preview-189--vega-docusaurus.netlify.app/docs/testnet/concepts/vega-chain#validating-nodes)
- [x] Check if I can commit to Candida's PR: #189 
- [x] Recreate proposed get started / how-to structure in Candida's PR
- [x] Ideate on content and structure to explain the journey validators take from candidate to consensus
- [ ] Ideate on content to explain how validators are assessed (performance)

**Comment by neildawson** [comment]
The following changes are merged into https://github.com/vegaprotocol/documentation/pull/189:

- Added [_Rewards_](https://deploy-preview-189--vega-docusaurus.netlify.app/docs/testnet/node-operators/rewards) page to explain how to earn standby and consensus rewards
- Created a [_Requirements_](https://deploy-preview-189--vega-docusaurus.netlify.app/docs/testnet/node-operators/requirements) category to highlight prerequisites for operating a node
- Restructured to differentiate between initial set-up tasks ([_Get Started_](https://deploy-preview-189--vega-docusaurus.netlify.app/docs/testnet/node-operators/get-started)) and ongoing maintenance tasks ([_How-to_](https://deploy-preview-189--vega-docusaurus.netlify.app/docs/testnet/node-operators/how-to))
- Edited file names, titles, and sidebar labels to use a consistent `how-to/do-a-thing` format

[Deploy preview](https://deploy-preview-189--vega-docusaurus.netlify.app/docs/testnet/node-operators)
