### ISSUE TITLE
Link up mentions of network parameters

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/documentation#254]
**Tasks**

- [X] Link up network parameter mentions in existing docs
- [X] Look for additional opportunities to link network parameters in existing docs
- [x] Link up network parameter mentions for new pages when Candida's PR is merged

GitHub issue: https://github.com/vegaprotocol/documentation/issues/247

We have a network parameter component which allows us to embed parameter names and values in docs, so we don't have to send someone off to block explorer.

There's a PR to improve the component: https://github.com/vegaprotocol/documentation/pull/177

Once this is done, someone needs to hunt down all the references to network parameters in docs and replace them with the shiny new component. They are not in the autogenerated docs, mostly in tutorials and concept pages, and Candida is working on a PR that will add many more.

Stuff that can be passed to the component:

- `frontMatter={frontMatter}` – every instance should have this, it determines if the parameter values should come from testnet or mainnet. This is derived from the front matter, so make sure it's defined there.
- `param="blockchains.ethereumConfig"` – every instance should have this, it determines which parameter we're referencing. By default this parameter will be printed at the start of the component.
- `name="Minimum length of voting period"` – replace the name of the parameter with something else, e.g. a human-readable name
- `hideValue={true}` – hide the value of the parameter, e.g. when you just want to highlight that a parameter exists
- `hideName={false}` – hide the name of the parameter, e.g. when including in a sentence
- `suffix="tokens"` – append text to the end of the component, in this case the word "tokens". I think 'tokens' might also do something clever like using singular/plural form correctly, but unsure.
- `formatter="governanceToken"` – Use `governanceToken` for token values ("0.000000000000000000000001" will be displayed as "1") and `percent` for percentages ("0.66" will be displayed as "33%")

And don't forget to import the component at the top of the page, too.

Use the parameter names from this doc: https://lb.testnet.vega.xyz/network/parameters as capitalisation on the public network parameters page won't work.

Afterwards, we could also flip things around and check to see if there are any parameters which aren't mentioned in docs, and look for places where doing so might be beneficial.

Mainnet parameters: https://explorer.vega.xyz/network-parameters
Testnet parameters: https://explorer.fairground.wtf/network-parameters

![Image](https://user-images.githubusercontent.com/47143694/190859688-929ef391-a6a0-4b11-9c17-e0e32ad0dd45.png)

**Comment by pennyandrews** [comment]
Neil:

Candida has added the new pages and says there are network parameters in this section which need to be added: https://docs.vega.xyz/docs/testnet/concepts/trading-on-vega

**Comment by neildawson** [comment]
Pull request: https://github.com/vegaprotocol/documentation/pull/274
