### ISSUE TITLE
Review site structure overall and work out target structure

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/documentation#255]
**Tasks**

- [X] Sitemap (https://miro.com/app/board/uXjVOi9oAwk=/)
- [X] Watch video highlights from user research - https://drive.google.com/drive/folders/16iiqW_zhUn40udSVp1_V3dcTibIdv07K
- [X] Review user research observations (https://miro.com/app/board/uXjVOs_72Ao=/)
- [X] Review Miro board where docs structure was planned (https://miro.com/app/board/o9J_lwMNb2U=/?share_link_id=269546973929)
- [X] Review principles and roadmap doc (https://docs.google.com/document/d/1CCDZod45C9jW3vd6oxUZSrJJjUPt-iy2XUrvEixgr9s/edit#heading=h.2088x42voiqh)
- [X] Review the Divio Documentation system (https://documentation.divio.com/)
- [X] Brush up on best practice for card sorting
- [ ] Clarify which docs are being migrated or written at the moment (i.e. what's coming imminently)
- [ ] Clarify what docs are expected to be added in future
- [ ] Content inventory
- [ ] Define target structure
- [ ] Share and agree with Candida and other key stakeholders
- [ ] Write stories in the backlog for implementation

- Review existing docs structure against priority challenges, are there any missing gaps? We've had a user try and fail to find governance for example from the docs landing page
- Review wayfinding / navigation mechanisms 
- Section structures
- Section landing pages
- The docs landing page
- Navigation methods
- Consider the two use cases - you're in the code trying to do something and want to look at the reference documentation vs. starting out how to type guides
- Identify any key missing technical diagrams?
- Work out the relationship between docs and other tools (there was mention of storybook)
- Prepare list of improvements for prioritisation
- Have a look at how others are doing this [👀 Reference sites](https://app.asana.com/0/1201793103707836/1202560368420914/f)
- 

Some potential inputs / resources / red herrings:

- Miro board where Candida, Barney and maybe others worked on the structure of the new docs site https://miro.com/app/board/o9J_lwMNb2U=/?share_link_id=269546973929 (I've invited you to it)
- A doc that Ramsey shared that Barney and Candida had used to align on requirements for docs (not sure whether it was before or after the miro board so might need so voice over from candida at some point https://docs.google.com/document/d/1CCDZod45C9jW3vd6oxUZSrJJjUPt-iy2XUrvEixgr9s/edit#heading=h.2088x42voiqh (I've invited you to it)
- Some content that explains this 'system' they are using around the different types of content - tutorials / how-tos / explainers / reference etc. https://documentation.divio.com/

Jon is super keen that as part of this work we create a map in Miro of the target structure that is a bit more site-mappy perhaps (easier to actually understand the structure) and shows what are landing pages v content pages and what pages are what 'type' of content. and in doing so making sure we understanding what types of content we need / want for different things and where the gaps are etc.

Being able to see these gaps will also help feed the community with content bounties they can task the community with to write non critical docs content or supporting blog posts etc.

**Comment by pennyandrews** [comment]
Calum:

From Jon - the need for some navigation that covers user profiles (Market Maker, Liquidity Provider, Trader, Community Member, Validator, Datanode Operator spring to mind as a start)
