### ISSUE TITLE
Update testnet contract addresses & network

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#276]
Testnet is moving from Ropsten to Sepolia, because Ropsten is being put out to pasture. Which would be OK if `@vegaprotocol/smart-contracts-sdk` were just updated. But it’s also been put out to pasture. So the addresses need to be updated to be fetched from somewhere else

## Tasks

- [ ] Determine where to get contract addresses from for all networks (see also https://github.com/vegaprotocol/frontend-monorepo/issues/1417)
- [ ] Remove the dependency listed above
- [ ] Update testnet addresses for sepolia
- [ ] Rename all instances of `Ropsten` with `Sepolia`, including in the frontmatter

## Next
- #277

**Comment by edd** [comment]
Closed in favour of #123, which got there first
