### ISSUE TITLE
Make docs api generation CI-able

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#282]
Currently the build process is like 

```
yarn install
yarn build
```

but that's because a lot of the plugin stuff is committed after it's generated, which is not the end goal. The end goal is being able to build the whole thing in CI. As of `0.56.0` that's more straightforward, but it's a while off. However it would be useful to be able to check if a change to a specific API specification file will break documentation in addvance. For this, we need a few simple wrappers around some docusaurus CI commands

# Tasks
- [ ] Make a single yarn script that can pull in an updated GraphQL schema and run the generator against it, do some basic checks, and return a 1 or 0 if it looks fine or is broken
- [ ] Make a single yarn script that can pull in an updated set of REST schema and run the generator against it, do some basic checks, and return a 1 or 0 if it looks fine or is broken
- [ ] Make a single yarn script that can pull in an updated protos.json and run the protobuffet generator against it, do some basic checks, and return a 1 or 0 if it looks fine or is broken
- [ ] Make a single yarn script that can pull in an updated `openapi.json` and... you get the picture

**Comment by edd** [comment]
See also #326
