### ISSUE TITLE
OpenAPI config should be generated from package.json version

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#301]
https://github.com/vegaprotocol/documentation/pull/285 made bumping the testnet version a little closer to the dream of 'I change the version number in `package.json` and everything just works'. Except...

https://github.com/vegaprotocol/documentation/blob/main/docusaurus.config.js#L222-L279

is easy to forget, like @edd when updating from 0.56 to 0.57. Luckily, the changes aren't in REST, so it's an invisible mistake

# Tasks
- [ ] Find somewhere to put a mainnet version in package.json
- [ ] Change docusaurus.config to populate openapi config from a function
  - [ ] List all `.swagger.json`s in  `specs/{package.json.version}` and create an entry for those
  - [ ] List all `.swagger.json`s in  `specs/{package.json.mainnetVersion}` and create an entry for those
