### ISSUE TITLE
Introduce and define governance parameters

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/documentation#316]
## Story

As a proposer
I want to understand the concept of network parameters, and to which proposal they apply
So that my proposal satisfies those parameters

## Acceptance Criteria

- [ ] I can find definitions of governance network parameters
- [ ] I can determine which parameters apply to my proposal
- [ ] I can determine requirements for these parameters (e.g. acceptable ranges)

## Tasks

- [ ] Explore changes and additions to the definition of network parameters in the Concepts area
- [ ] Check for opportunities to better define network parameters in governance tutorials (e.g. minclose and maxclose are explained in the new market tutorial, but not in all others)
- [ ] Stakeholder review

## Additional details / background info
- We now mention most relevant governance parameters in the [governance proposal guides in testnet docs](https://docs.vega.xyz/docs/testnet/tutorials/proposals). We are lacking an introduction to the concept of governance parameters, at a higher level.
- The [Thresholds for network parameters](https://docs.vega.xyz/docs/testnet/concepts/vega-protocol#thresholds-for-network-parameters) section does this to some degree. We have made some improvements to this in https://github.com/vegaprotocol/documentation/pull/274. However, it does not define the parameters or explain their purpose, and assumes familiarity with the concept.
- This issue suggests editing this section, or writing a new section, to introduce the concept and define common parameters.
