### ISSUE TITLE
"Vega supports cash settled futures"

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/documentation#339]
## Chore 

We need to explain at a minimum that right now, Vega supports cash settled futures, so that users who start in the docs, website or on console are clear what you can use Vega for. 

## Tasks 

- [ ] Work out where this would be relevant 
- [ ] Add explanation 
- [ ] Update Governance proposal type "Propose a new market" description e.g. "Propose a cash settled futures market on any underlying" or similar 
- [ ] Update docs landing page to reflect cash settled futures in the introduction to Trading e.g. for now that might be "Explore the risk-free Vega testnet. Mainnet trading launching soon, **starting with cash settled futures**"
