### ISSUE TITLE
More data source API refactoring

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#346]
After https://github.com/vegaprotocol/vega/pull/5980 there will be changes across everything that talks about Oracles. @RomanLeca has made test fixes that correspond to this change here: https://github.com/vegaprotocol/system-tests/pull/1337/files for reference.

# Tasks
- [ ] Update newMarket proposal code
- [ ] Update updateMarket proposal code
- [ ] Update Data Sources page

This is post-0.59.0.

**Comment by candida-d** [comment]
closed in #384
