### ISSUE TITLE
Improve API search by using context

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#361]
## Story

As a user who is interested in the REST api
I want to be able to only search the REST documentation for specific terms
So that I do not have to filter through results I don't care about

## Acceptance Criteria

- [ ] I can somehow indicate that I want REST results only

## Tasks

- [x] Try out `searchContextByPaths` in https://github.com/easyops-cn/docusaurus-search-local
- [ ] See what typesense offers in comparison
- [ ] See what algolia offers in comparison
