### ISSUE TITLE
trading_data_v2 REST streaming endpoints do not work nicely in generated docs

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#423]
<img width="510" alt="Screenshot 2022-12-10 at 10 52 43" src="https://user-images.githubusercontent.com/6678/206851496-814db3b8-3973-4f24-899d-8445f3b8e2ea.png">

# Tasks
- [x] See if there's a way to disable the 'Submit' for the streaming endpoints
- [x] #536
- [ ] Add more detail to individual reference endpoints for in-place guidance

# Spike
- [ ] Add a new post-processing script that pulls items out of 'path' that have '/stream/' in the URL
- [ ] Add them to a new thing called `x-webhooks`
- [ ] See if it looks like https://docusaurus-openapi.tryingpan.dev/petstore_versioned/new-pet

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/demo/examples/petstore-1.0.0.yaml#L1194-L1209

**Comment by candida-d** [comment]
This is back. Especially confusing as the URL has https https://github.com/vegaprotocol/documentation/issues/691
