### ISSUE TITLE
API integration introduction content

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/documentation#430]
## Story

As a user 
I want to quickly understand the Vega APIs available, how I might access them 
So that I can decide whether to invest more time in using Vega and get started building

## Acceptance Criteria

- [ ] I can understand how the API documentation is organised (using the REST endpoint) 
- [ ] I can understand the methods for accessing our APIs - GraphQL and REST and GRPC
- [ ] There is an explanation of the pros and cons of each, and what they might be used for
- [ ] I can understand the available APIs available - Core node APIs, Data node APIs, Vega Wallet APIs, Tendermint API... and the sorts of endpoints within
- [ ] I can understand how pagination, transactions and versioning works?
- [ ] I can see that I need a wallet running to send / receive transactions
- [ ] There is an explanation of the primary elements and the end points used for:-
* Assets 
* Parties
* Accounts
* Proposals
* Markets
* Orders

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by candida-d** [comment]
This is now live. There have been lots of other changes to API docs done in other PRs as well, plus more to come, but I've called this ticket done as the content sketched out has now been added.
