### ISSUE TITLE
Update node operator docs with postgres and snapshot configs

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/documentation#436]
## Story

In order for data node operations to have access to the optimal? / recommended data node snapshot AND postgres configs we need to review the following PRs and see what should be captured in the node operator docs:

- https://github.com/vegaprotocol/ansible/pull/382
- https://github.com/vegaprotocol/networks-internal/pull/219

## Tasks

- [ ] Review the config settings
- [x] Review the current docs
- [x] Make updates to the documentation for node operators
- [ ] ?? Let the current validator set know in readiness for the dry run / include in the dry run deployment instructions (maybe a task outside of the scope of the docs repo) ??

## Additional details / background info

Fairground was found to be running out of memory this was short listed to the snapshot frequency and retention policies and the postgres config. Both have been addressed in the core / vega infra but should be accounted for in the docs.

**Comment by candida-d** [comment]
Snapshot interval number doesn't need to be covered in the docs (per @jeremyletang), and as the postgres task is done, I'm closing this
