### ISSUE TITLE
Give code examples for depositing

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/documentation#589]
## The Chore

Provide some code examples for depositing for the 'Programmatic trading basics' tutorial.

Note that in this section the title 'Deposit using smart contracts' title is a bit misleading as all methods of deposit use smart contracts. IE the collateral bridge. Might be worth changing that title to 'Deposit using Etherscan' and adding an additional section for doing it programatically with whatever langauge

## Tasks

- [x] Determine what langauges we might want examples for
- [ ] Get examples from people that know those languages
- [ ] Add a code snippet box with the examples
