### ISSUE TITLE
Deprecate `ethereum_network`frontmatter

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#607]
# Description
There is a frontmatter item on one page only - `update-asset-bridge` - that is handled by the version update script. It's not actually used any more and should be removed

# Tasks
- [ ] Ensure that no custom component uses the `ethereum_network` frontmatter
- [ ] Remove all instances of `ethereum_network`
- [ ] Remove updating from `version-update.sh`
