### ISSUE TITLE
Address `version-switch.sh`

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#608]
## Description
This script: https://github.com/vegaprotocol/documentation/blob/main/scripts/version-switch.sh

was written a while ago and doesn't smoothly update the versions as was hoped. It might have, 19 versions ago..

# Tasks
- [x] #607
- [x] https://github.com/vegaprotocol/documentation/pull/606#discussion_r1188890045
- [x] Check what else changed in https://github.com/vegaprotocol/documentation/pull/606
- [ ] Check for `/testnet/...` links in the generated GraphQL and protos documentation files

# Decide what to do about
- [ ] The generated proposal examples get copied over to `current` from `latest` without the network changing. These were initially generated so that they *didn't* appear in `current`. Decide if we:
    - [ ] We want them in `current` at all
    - [ ] If they stay, should we change the network, or how should we make it clear that they need significant customisation before they're ready to use, even if they're valid
