### ISSUE TITLE
Create the network history restore docs for validators

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/documentation#611]
## The Chore

We need to write the tutorial for the validator that covers data-node restart with the network-history. This is a pretty important task because now I recommend to all the validators to do unsafe-reset-all and replay 30k blocks but in a week or two it will be hard to stop validator for a few hours...

## Tasks

- [ ] Short description of why network history and how it is working
- [ ] How to prepare and gather data to make network history working
- [ ] Steps to restart from network history when we already have some data in the node and we have only some of them missing
- [ ] Steps to restart from network history when we are starting node after unsafe reset-all
- [ ] Loading all data from block 0 - aka restoring archival node
