### ISSUE TITLE
Information about Quantum number formatting

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/documentation#640]
## Story

As a Trader using Console
I want be able to find information in Vega docs about quantum number formatting
So that can understand what it is, how it is calculated and why we use it

## Acceptance Criteria

- [ ] I can find information in docs about quantum number formatting
- [ ] I can find information in docs about how we define quantum numbers 'Number DP = MAX(0, LOG10(100/Quantum))` 
- [ ] I can find a explanation of why Vega uses this format i.e. the benefits

## Tasks

- [ ] TBC by Candida 

## Additional details / background info

- vegaprotocol/frontend-monorepo#2132

**Comment by candida-d** [comment]
Closing as per https://github.com/vegaprotocol/frontend-monorepo/issues/3952#issuecomment-1579141681
