### ISSUE TITLE
Spot market proposal tutorials

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/documentation#693]
## Story

As a governance user
I want guidance on how to submit the new governance proposal types
So I can create or amend a spot market

## Acceptance Criteria

- [x] I can find details of the new proposals, what fields are required, and how/where they should be submitted
  - [x] New spot market
  - [ ] Amend spot market
  - [x] Update market state (also applies to futures markets, states can be suspended, resumed, terminated)

## Tasks

- [ ] Draft
- [ ] Team and stakeholder review
- [ ] Publish
