### ISSUE TITLE
Show total accrued Liquidity Provision fees across the whole market

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/documentation#707]
## Story

As a potential liquidity provider
I want to see examples of returns
So I can make an informed decision about providing liquidity on vega

## Acceptance Criteria

- [ ] I can see the total Liquidity Provision fees paid out over the lifetime of each market

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
- [Suggestion from Barney in Slack](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1689168706295309?thread_ts=1689162667.366119&cid=C8WS7M50E)
