### ISSUE TITLE
Build process tidyup

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#86]
After #84 the build process has changed quite significantly, but the build scripts have some loose ends

# Pre #84: 
- GRPC is generated as a build step, just before running `yarn build` in CI
- REST documents only exist for the version passed in by `VEGA_VERSION` at build time
- Protobuf documentation is generated as a build step, in to `/protodocs`

# Post #84:
- GRPC is generated by docusaurus-protobuffet into `/docs/grpc`, the results are committed
- GraphQL section is generated by docusaurus2-graphql-generator in to `/docs/graph all, the results are committed
- REST remains unchanged

# Adding a new version
Every time a new big release is planned, a [new version will need to be tagged](https://docusaurus.io/docs/versioning#tagging-a-new-version). This will take a complete copy of `/docs` and copy it in to a new folder in `/versioned_docs`. 
- The version number in the label for the current version will need to be updated
- The docusaurus ‘alias’ for the versions will need to move.
  - `testnet` alias should remain `current`, but have it’s version number updated
  - `mainnet` alias should be updated to point to the version that was just tagged
  - Versions that are no longer deployed can be left as is, meaning they will be referred to by their version string (e.g. `/docs/v0.33.0/api`)
- REST is updated by adding new versions in to docusaurus.config.js. No files are committed for this.
- Now that the docs are copied, and the alias for each version is changed, some links may have broken. Most, but not all, links use references that Docusaurus will automatically prefix with the relevant version number - meaning an internal link in the `testnet` From ‘a.md’ to ‘b.md’ should not need the  version to be added in front of it. However some generated docs (graphql, protodocs) may need their links to be changed. There is a script in `/scripts/versions.sh` That is an example of the sort of pattern you can use to fix links, but this isn’t fully automatic yet

# Tasks
- [x] The Adding a new version section is a lot of manual work. This should be reduced.
- [x] Docs no longer need to be generated in CI as they are committed, therefore the build process should only do what is necessary (`yarn install` && `yarn build`) rather than generating documentation again
- [x] A new user should be able to clone and start up the docs locally without running `build.sh`
- [x] A new user should not have to set a `GITHUB_API_TOKEN` environment just to get a running development server
- [x] `VEGA_VERSION` should no longer need to be passed to `yarn start`

**Comment by edd** [comment]
This ticket is old enough to be unuseful. I think #326 better encapsulates the work to be done.
