### ISSUE TITLE
Core/Data-Node config parameter description

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/documentation#861]
# Feature overview

I do not think it is very urgent but it would help people understand how the configuration can change the behaviour of the node. 

It would be nice to get all available parameters from the config and describe what they do in the protocol.

## Tasks

- [ ] Research a good way to represent config parameters. Maybe check other documentation for other open source software?
- [ ] Prepare a description for each parameter for <vega_home>/config/node/config.toml - the core part
- [ ] Prepare a description for each parameter for <vega_home>/config/data-node/config.toml - the data-node part
