### ISSUE TITLE
Add documentation for Ethereum interfaces

### ISSUE THREAD

**Issue by edd** [vegaprotocol/documentation#87]
Having the Ethereum bridge contracts in the API section would be nice.

# Tasks
- [x] Have compiled contracts added to [vegaprotocol/multisigcontrol](https://github.com/vegaprotocol/multisigcontrol)
- [x] Add a build step (see #86) to:
  - [x] Fetch built contracts from above
  - [x] Run [leafleth](https://github.com/clemlak/leafleth)
  - [x] Move relevant contracts in to the `/docs/` folder:
    - [x] `IVega_Staking_Bridge`
    - [x] `IERC20_Bridge_Logic`
    - [x] `IMultisigControl`
