### ISSUE TITLE
Node operator documentation for 0.74.0 deployment

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/documentation#910]
# Feature overview

**In order to** ensure that the validators carry out the IPFS and block explorer migrations, machine specifications (related to the OOM/Disk space issues seen) and the EVM chain data sourcing correctly
**We will** create easy to use node operator 
**So that** the node operators can easily migrate from 0.73.x to 0.74.0

## Tasks
A checklist of the tasks that are needed to fully document the requested topic.

- [ ] Document IPFS migrations (both for operators using and NOT using Visor)
- [x] Document Block Explorer migrations
- [ ] Document any EVM data sourcing config that is required (Gnosis/Arbitrum event providers)
- [ ] Review the [validator node hardware specifications](https://docs.vega.xyz/testnet/node-operators/requirements/infrastructure)
- [ ] Review the [data node hardware specifications](https://docs.vega.xyz/testnet/node-operators/requirements/data-node-infrastructure)
- [ ] Any other 0.74.0 instructions
  - [ ] Data node
  - [ ] Core
  - [ ] Tendermint upgrade to 0.38

## Additional information:

- https://github.com/vegaprotocol/vega/issues/10304
